name: 'Pkl Swift'
author: 'Emily McLean'
description: 'Generates swift source code for a Pkl model. Based on version 0.26.3 of the Pkl tool/lang.'
inputs:
  input-file:
    description: 'The Pkl file to process'
    required: true
  output-folder:
    description: 'Where the resulting data will be written to.'
    required: true
  pkl-version:
    description: The pkl version to install.
    required: false
    default: '0.26.3'
runs:
  using: 'composite'
  steps:
    - run: |
        docker run --rm -v "./:/data" ghcr.io/emilymclean/pkl-codegen-swift:${{ inputs.pkl-version }} "/data/${{ inputs.input-file }}" "/data/${{ inputs.output-folder }}"
      shell: bash
branding:
  icon: 'cpu'
  color: 'green'